version: "3"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: yoprogramo/php7.4:${VERSION}

  php-xdebug:
    build:
      context: .
      dockerfile: Dockerfile-xdebug
    image: yoprogramo/php7.4:${VERSION}-xdebug

  
