name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
    - run: docker login -u ${{ vars.DR_USER }} -p ${{ secrets.DR_PASS }} https://hub.docker.com
    - run: docker compose build && docker compose push
